version: "3.8"

services:
  fastapi_app:
    restart: unless-stopped
    container_name: fastapi_app_container
    build:
      context: .
    ports:
      - "8000:80"
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - .:/code

  db:
    container_name: fastapi_postgres_container
    image: postgres:latest
    env_file:
      - .env
    ports:
      - 5432:5432
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 3s
      timeout: 3s
      retries: 30
    volumes:
      - ./scripts/db_init.sh:/docker-entrypoint-initdb.d/db_init.sh 
      - pgdata:/var/lib/postgresql/data
volumes:
  pgdata:
    driver: local
