#!/bin/bash

set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${FASTAPI_USER} WITH PASSWORD '${FASTAPI_PASSWORD}';
    CREATE DATABASE ${FASTAPI_DB};
    ALTER DATABASE ${FASTAPI_DB} OWNER TO ${FASTAPI_USER};
EOSQL